server {
    listen 80;
    server_name your-domain.com;

    root /var/www/app/dist;
    index index.html;

    # React/Vite SPA
    location / {
        try_files $uri $uri/ /index.html;
    }

    # MAIN API
    location /api/ {
        proxy_pass http://qa-92rf.dentypro.com:8092;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # DENTYPRO
    location /api/dentypro/ {
        rewrite ^/api/dentypro/(.*)$ /$1 break;

        proxy_pass http://qa-92rf.dentypro.com;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
    }

    # IMPORT XLSX
    location /api/import-xlsx/ {
        rewrite ^/api/import-xlsx/(.*)$ /api/user-products/import-xlsx/$1 break;

        proxy_pass http://51.20.96.242:8080;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
    }

    # GOOGLE MAPS
    location /api/google-maps/ {
        rewrite ^/api/google-maps/(.*)$ /$1 break;

        proxy_pass https://maps.googleapis.com/maps/api/;

        proxy_ssl_server_name on;

        proxy_set_header Host maps.googleapis.com;
    }
}
